# Generated by Django 2.2.4 on 2020-08-27 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choresApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
