# Generated by Django 2.2.4 on 2020-08-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='releaseDate',
            field=models.DateField(),
        ),
    ]
