# Generated by Django 2.2.4 on 2020-08-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_app', '0002_auto_20200820_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='releaseDate',
            field=models.CharField(max_length=255),
        ),
    ]
