# Generated by Django 2.2 on 2020-08-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playersFansApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fan',
            name='lastname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
